### ISSUE TITLE
登录后一直“加载用户信息中”

### ISSUE THREAD

**Issue by NIANXI39** [gaozhangmin/aliyunpan#159]
扫码两次后登录一直加载用户信息中，有什么解决办法?
下面是运行日志
18 16:23:58 : danger : unhandledrejection 
//== Error ==//
 Transaction aborted 
//== Stack ===//
 AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///D:/software/xbyyunpan/resources/app.asar/dist/index.js:22:39355)
    at IDBTransaction.<anonymous> (file:///D:/software/xbyyunpan/resources/app.asar/dist/index.js:22:6227)
18 16:23:58 : danger : aRefreshAllUserSession 
//== Error ==//
 UpgradeError Not yet support for changing primary key 
//== Stack ===//
 DatabaseClosedError: UpgradeError Not yet support for changing primary key
    at file:///D:/software/xbyyunpan/resources/app.asar/dist/index.js:22:76477
    at executePromiseTask (file:///D:/software/xbyyunpan/resources/app.asar/dist/index.js:22:2793)
    at new DexiePromise (file:///D:/software/xbyyunpan/resources/app.asar/dist/index.js:21:4542)
    at C._whenReady (file:///D:/software/xbyyunpan/resources/app.asar/dist/in...
18 16:23:58 : danger : aRefreshAllUserToken

**Comment by gaozhangmin** [comment]
清理缓存试下

**Comment by gaozhangmin** [comment]
设置里点“删除全部数据(重置)”
