### ISSUE TITLE
[Bug] {{启动很慢是正常吗}}

### ISSUE THREAD

**Issue by c02y** [gaozhangmin/aliyunpan#243]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.15~3.11.17

### 系统 System

Arch Linux, kernel: 6.4.4-zen1-1-zen

### 复现步骤 Reproduce step

1. 下载XBYDriver-3.11.17-linux-x86_64.AppImage， 版本3.11.15或者3.11.16也行
2. chmox +x ./XBYDriver-3.11.17-linux-x86_64.AppImage
3. ./XBYDriver-3.11.17-linux-x86_64.AppImage

终端执行之后打印内容：
```
$ ./XBYDriver-3.11.17-linux-x86_64.AppImage
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3533957:0730/225013.899408:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[3533957:0730/225023.529576:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3533957:0730/225023.529695:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3533957:0730/225023.529803:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3533957:0730/225024.864313:ERROR:CONSOLE(141)] "Electron renderer_init.js script failed to run", source: node:electron/js2c/renderer_init (141)
[3533957:0730/225024.864336:ERROR:CONSOLE(141)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/renderer_init (141)
the server is runnint on port 16800
the server is runnint on port 16800
```

### 你看到了什么错误？What errors do you see?

从执行到看到窗口打开耗时太久，花了近45秒

### 你期望看到什么？What did you expect to see?

不知道这是正常的还是我的问题
如果不正常，有什么方法看到什么原因导致的

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by c02y** [comment]
请问什么叫“应用缓存”？我看看有多大


另外附上最新版本的终端输出：
```
>> ~/Applications/XBYDriver-3.11.18-linux-x86_64.AppImage
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[342397:0803/200831.199087:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Unhandled Rejection at: Promise {
  <rejected> Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
      at Object.openSync (node:fs:585:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
      at Object.writeFileSync (node:fs:2170:35)
      at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
      at IpcMainImpl.emit (node:events:527:28)
      at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
      at EventEmitter.emit (node:events:527:28) {
    errno: -30,
    syscall: 'open',
    code: 'EROFS',
    path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
  }
} reason: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
}
(node:342397) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
(Use `xbyyunpan --trace-warnings ...` to show where the warning was created)
(node:342397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Unhandled Rejection at: Promise {
  <rejected> Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
      at Object.openSync (node:fs:585:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
      at Object.writeFileSync (node:fs:2170:35)
      at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
      at IpcMainImpl.emit (node:events:527:28)
      at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
      at EventEmitter.emit (node:events:527:28) {
    errno: -30,
    syscall: 'open',
    code: 'EROFS',
    path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
  }
} reason: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
}
(node:342397) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
(node:342397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Unhandled Rejection at: Promise {
  <rejected> Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
      at Object.openSync (node:fs:585:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
      at Object.writeFileSync (node:fs:2170:35)
      at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
      at IpcMainImpl.emit (node:events:527:28)
      at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
      at EventEmitter.emit (node:events:527:28) {
    errno: -30,
    syscall: 'open',
    code: 'EROFS',
    path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
  }
} reason: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
}
(node:342397) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
(node:342397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
Unhandled Rejection at: Promise {
  <rejected> Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
      at Object.openSync (node:fs:585:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
      at Object.writeFileSync (node:fs:2170:35)
      at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
      at IpcMainImpl.emit (node:events:527:28)
      at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
      at EventEmitter.emit (node:events:527:28) {
    errno: -30,
    syscall: 'open',
    code: 'EROFS',
    path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
  }
} reason: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
}
(node:342397) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
(node:342397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Unhandled Rejection at: Promise {
  <rejected> Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
      at Object.openSync (node:fs:585:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
      at Object.writeFileSync (node:fs:2170:35)
      at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
      at IpcMainImpl.emit (node:events:527:28)
      at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
      at EventEmitter.emit (node:events:527:28) {
    errno: -30,
    syscall: 'open',
    code: 'EROFS',
    path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
  }
} reason: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
}
(node:342397) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, open '/tmp/.mount_XBYDrigz5xwx/resources/userdir.config'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at IpcMainImpl.<anonymous> (/tmp/.mount_XBYDrigz5xwx/resources/app.asar/dist/electron/main/index.js:7:1866)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11237)
    at EventEmitter.emit (node:events:527:28)
(node:342397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
the server is runnint on port 16800
the server is runnint on port 1680
```

**Comment by gaozhangmin** [comment]
@c02y 你应用缓存目录不存在 所以保这个错误。重新指定个目录

**Comment by c02y** [comment]
你这个“应用缓存”指的是`~/.config/alixby3/`吗？这个目录存在啊，只有15MB, 我在设置那里清空了一下再打开启动时间还是很长

如果不是这个，可不可以详细说说怎么操作？

另外补充设置里面的日志：
```
03 21:38:48 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///tmp/.mount_XBYDri3Ec5nY/resources/app.asar/dist/index.js:95:52335)
    at ue.onerror (file:///tmp/.mount_XBYDri3Ec5nY/resources/app.asar/dist/index.js:95:60156)
03 21:38:48 : danger : Uncaught Error: Unhandled error. (undefined)
03 21:38:48 : danger : onerror
03 21:38:47 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at re.emit (file:///tmp/.mount_XBYDri3Ec5nY/resources/app.asar/dist/index.js:95:52335)
    at ue.onerror (file:///tmp/.mount_XBYDri3Ec5nY/resources/app.asar/dist/index.js:95:60156)
03 21:38:47 : danger : Uncaught Error: Unhandled error. (undefined)
03 21:38:47 : danger : onerror
03 21:38:39 : success : 小白羊启动

```

**Comment by c02y** [comment]
怎么关闭了？

**Comment by c02y** [comment]
不知道最新版本v3.11.19发布页面里面的“修复缓存目录设置不生效bug”是不是修复这个，不过我试用了一下，打开还是需要50秒左右
