### ISSUE TITLE
[Bug] yarn build 好像没法成功构建

### ISSUE THREAD

**Issue by zzy-ac** [gaozhangmin/aliyunpan#309]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.26

### 系统 System

archlinux

### 复现步骤 Reproduce step

yarn install
yarn run build 

### 你看到了什么错误？What errors do you see?

yarn run v1.22.19
$ vue-tsc --noEmit && vite build && electron-builder -wml
vite v3.2.7 building for production...
✓ 911 modules transformed.
transforming (1345) node_modules/ant-design-vue/es/list/ItemMeta.jsvite v3.2.7 building for production...
✓ 1 modules transformed.
transforming (1423) node_modules/@ant-design/icons-vue/es/icons/CheckOutlined.jsdist/electron/preload/index.js   2.92 KiB / gzip: 0.77 KiB
transforming (1842) node_modules/ant-design-vue/es/vc-select/hooks/useDelayReset.jsvite v3.2.7 building for production...
✓ 109 modules transformed.
transforming (2195) node_modules/lodash-es/_unicodeToArray.jsdist/electron/main/index.js   65.69 KiB / gzip: 21.79 KiB
Could not resolve '../ResPan/topbtns/CreatNewDirModal.vue' from src/layout/MyModal.vue?vue&type=script&lang.ts
error during build:
Error: Could not resolve '../ResPan/topbtns/CreatNewDirModal.vue' from src/layout/MyModal.vue?vue&type=script&lang.ts
    at error (file:///home/zzy/Desktop/aliyunpan-odomu-git/src/aliyunpan/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///home/zzy/Desktop/aliyunpan-odomu-git/src/aliyunpan/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
    at file:///home/zzy/Desktop/aliyunpan-odomu-git/src/aliyunpan/node_modules/rollup/dist/es/shared/rollup.js:22119:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 你期望看到什么？What did you expect to see?

能够正常构建程序

### 还有其他的内容吗？Anything else?

我的发行版是archlinux,electron版本为25.6.0

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by zzy-ac** [comment]
https://github.com/gaozhangmin/aliyunpan/pull/310/commits/d4804bdd989bd16d9699aae7449ff35d6622854d
看到有人提交pr修复了，非常感谢
