### ISSUE TITLE
[Bug] 加载不了备份盘

### ISSUE THREAD

**Issue by niconicozha** [gaozhangmin/aliyunpan#323]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.11.26

### 系统 System

Windows 11

### 复现步骤 Reproduce step

点击备份盘/根目录

### 你看到了什么错误？What errors do you see?

//== Error ==// Failed to read large IndexedDB value DataError: Failed to read large IndexedDB value //== Stack ===// DataError: Failed to read large IndexedDB value DataError: Failed to read large IndexedDB value at mapError (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:21:531) at handleRejection (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:3302) at IDBRequest.<anonymous> (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js...

 //== Error ==// UnknownError //== Stack ===// AbortError: UnknownError at IDBTransaction.<anonymous> (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:39381) at IDBTransaction.<anonymous> (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:22:6231)
![屏幕截图 2023-11-02 193603](https://github.com/gaozhangmin/aliyunpan/assets/107761924/c14f62af-1043-4d7d-bd00-35f0c92e5a84)

### 你期望看到什么？What did you expect to see?

没有错误弹窗

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaozhangmin** [comment]
@niconicozha  数据库太大了。清理掉所有的缓存，重启

**Comment by alex14563** [comment]
> @niconicozha 数据库太大了。清理掉所有的缓存，重启

6啊，我也是报这个错哦，解决啦~~~
