### ISSUE TITLE
会员用户无法访问备份盘[Bug] 

### ISSUE THREAD

**Issue by Tnkaili** [gaozhangmin/aliyunpan#372]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.12.4

### 系统 System

win11  22h2 家庭版

### 复现步骤 Reproduce step

登录会员账号后等待加载全部文件夹出错

### 你看到了什么错误？What errors do you see?

unhandledrejection //== Error ==// Cannot read properties of undefined (reading 'length') //== Stack ===// TypeError: Cannot read properties of undefined (reading 'length') at replaceHanNumber (file:///D:/LenovoSoftstore/Install/xiaobaiyang/xbyyunpan/resources/app.asar/dist/index.js:35:427261) at _OrderName (file:///D:/LenovoSoftstore/Install/xiaobaiyang/xbyyunpan/resources/app.asar/dist/index.js:35:427093) at file:///D:/LenovoSoftstore/Install/xiaobaiyang/xbyyunpan/resources/app.asar/dist/index.js:35:426741 at ...

### 你期望看到什么？What did you expect to see?

none

### 还有其他的内容吗？Anything else?

备份盘文件无法访问，资源盘，照片等正常访问，其他功能正常。非会员账号正常。重置数据和缓存无效。

https://github.com/gaozhangmin/aliyunpan/assets/126746817/bdd3e059-1397-4370-a625-0dfc315a2b43

https://github.com/gaozhangmin/aliyunpan/assets/126746817/0417fd85-e07d-4c0d-a535-6106f239dff6

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Tnkaili** [comment]
补充，手机端是最新的5.0.1版本

**Comment by Tnkaili** [comment]
没人吗
