### ISSUE TITLE
[Bug] {{无法下载以及在线播放}}

### ISSUE THREAD

**Issue by a756624802** [gaozhangmin/aliyunpan#411]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.13.1

### 系统 System

Windows11 x64

### 复现步骤 Reproduce step

无法下载以及在线播放

### 你看到了什么错误？What errors do you see?

下载失败：
61c1dd674d5aaefaf9d14c2f9f63ee87e2695af9 生成下载链接失败, {"drive_id":"1939422","file_id":"61c1dd674d5aaefaf9d14c2f9f63ee87e2695af9","url":"","size":0,"qualities":[],"subtitles":[]}
在线播放失败：
unhandledrejection //== Error ==// Cannot read properties of undefined (reading 'url') //== Stack ===// TypeError: Cannot read properties of undefined (reading 'url') at Object.startPlayer (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:366:3223) at Video (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:366:10812) at async menuOpenFile (file:///D:/Program%20Files/xbyyunpan/resources/app.asar/dist/index.js:366:6841)

### 你期望看到什么？What did you expect to see?

可以正常下载以及在线播放

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by springculture** [comment]
账号退出再登录

**Comment by wwwstar2003** [comment]
mac arm64，启动提示软件通信端口5000被占用，视频都无法播放
