### ISSUE TITLE
[Bug] 3.13.3 Macbook Air M3 报错

### ISSUE THREAD

**Issue by macgg** [gaozhangmin/aliyunpan#419]
### Please search before asking

- [X] I searched in the [issues](https://github.com/gaozhangmin/aliyunpan/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### 使用的版本

3.13.3

### 系统 System

MacOS 14.4.1

### 复现步骤 Reproduce step

每次打开程序, 会提示版本相关错误
<img width="890" alt="Screenshot 2024-04-08 at 5 42 01 PM" src="https://github.com/gaozhangmin/aliyunpan/assets/16809241/dde083fd-339b-49fd-8bf8-37b358695778">

### 你看到了什么错误？What errors do you see?

用app clean &unisntall 卸载小白羊, 重装后, 重启后, 仍然是如此错误提示

### 你期望看到什么？What did you expect to see?

不再出现此提示

### 还有其他的内容吗？Anything else?

16 05:24:19 : warning : HttpError4 status=403 code=UserNotVip message=Request failed with status code 403
16 05:22:37 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///Applications/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98.app/Contents/Resources/app.asar/dist/index.js:22:76513
    at ...
16 05:22:37 : danger : aReloadUploaded 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///Applications/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98.app/Contents/Resources/app.asar/dist/index.js:22:76513
    at ...
16 05:22:37 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///Applications/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98.app/Contents/Resources/app.asar/dist/index.js:22:76513
    at ...
16 05:22:37 : danger : unhandledrejection 
//== Error ==//
 VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30). 
//== Stack ===//
 DatabaseClosedError: VersionError The requested version (20) is less than the existing version (30).
 VersionError: The requested version (20) is less than the existing version (30).
    at file:///Applications/%E5%B0%8F%E7%99%BD%E7%BE%8A%E4%BA%91%E7%9B%98.app/Contents/Resources/app.asar/dist/index.js:22:76513
    at ...
16 05:22:33 : success : 小白羊启动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by macgg** [comment]
安装的是 XBYDriver-3.13.3-mac-arm64.dmg

**Comment by lwokf** [comment]
删除 系统盘:\Users\用户名\AppData\Roaming目录下的文件夹“alixby3”，再重新安装看看

**Comment by macgg** [comment]
win下和mac intel版本的3.13.3 都没问题的哈 只有这个新买的m3 air安装的mac arm是有这个提示的，已经卸载清理再安装两次了，所以才费劲过来上报的
________________________________
